steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend-service'
      - '--image=gcr.io/$PROJECT_ID/frontend-app'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--vpc-connector=my-vpc-connector'
      - '--allow-unauthenticated'

# THIS IS THE ESSENTIAL PART. It must be at the same indentation level as 'steps:'
logsBucket: 'gs://sohitmishra007-cloud-build-logs'
