steps:
  - name: 'gcr.io/cloud-builders/docker'
    # CHANGE THIS LINE:
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-app', 'frontend'] # <--- Changed '.' to 'frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend-service'
      - '--image=gcr.io/$PROJECT_ID/frontend-app'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--vpc-connector=my-vpc-connector'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY # This is fine for now, addressing the "no logs" issue
