steps:
  - name: 'gcr.io/cloud-builders/docker'
    # THIS LINE MUST BE CHANGED TO 'frontend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-app', 'frontend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend-service'
      - '--image=gcr.io/$PROJECT_ID/frontend-app'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--vpc-connector=my-vpc-connector'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
